### ISSUE TITLE
Version Update Issue

### ISSUE THREAD

**Issue by hunhoffe** [vmware/declarative-cluster-management#159]
### Describe the bug

I am having trouble creating a project using the maven artifact with versio 0.13.0.

When I update to 0.13.0, I get this error while the solver is running:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3.isStringEmpty(java.lang.Object)'
	at com.google.ortools.sat.IntegerVariableProto.getSerializedSize(IntegerVariableProto.java:293)
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:68)
	at com.google.ortools.sat.CpSatHelper.variableDomain(CpSatHelper.java:54)
	at com.google.ortools.sat.IntVar.getDomain(IntVar.java:118)
	at com.vmware.dcm.backend.ortools.Ops.eq(Ops.java:366)
	at com.vmware.dcm.backend.ortools.Ops.eq(Ops.java:362)
	at com.vmware.dcm.backend.GeneratedBackend.solve(GeneratedBackend.java:91)
	at com.vmware.dcm.backend.ortools.OrToolsSolver.runSolver(OrToolsSolver.java:208)
	at com.vmware.dcm.Model.solve(Model.java:219)
	at com.vmware.dcm.Model.solve(Model.java:199)
	at com.vmware.dcm.Model.solve(Model.java:240)
	at com.vmware.bespin.scheduler.Simulation.runModelAndUpdateDB(SimulationRunner.java:65)
	at com.vmware.bespin.scheduler.SimulationRunner.main(SimulationRunner.java:493)
```

### Reproduction steps

```bash
If desired, let me know and I will point you to a commit in my repo after giving access to the repo.
```

### Expected behavior

I expect the solver to run successfully.

### Additional context

I am using an older version of jooq (3.13.3) due to some errors I came across in updating that library in my project. However, if a newer backend model is needed for 0.13.0, it would be nice if that requirement were documented.

**Comment by lalithsuresh** [comment]
This is an issue with classpaths + the wrong version of protobufs being in your project. Could you see if there are multiple protobuf dependencies in your path?

**Comment by hunhoffe** [comment]
Thanks for the response! There's only one protobuf in the dependency tree (copied below). I've also sent you an invite to the repo for this project and created a branch with the current state of this error (https://github.com/hunhoffe/bespin-dcm/tree/versiondebugging) if you want to try to reproduce it yourself.

As a reminder, everything works fine with 0.12.0.... although maybe that's just luck if this is indeed a dependency issue.

> [INFO] com.vmware.bespin:scheduler:jar:1.0-SNAPSHOT
> [INFO] +- com.vmware.dcm:dcm:jar:0.13.0:compile
> [INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.13.3:runtime
> [INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
> [INFO] |  +- org.jooq:jooq-meta:jar:3.13.1:compile
> [INFO] |  +- com.google.guava:guava:jar:29.0-jre:runtime
> [INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:runtime
> [INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:runtime
> [INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:runtime
> [INFO] |  |  +- org.checkerframework:checker-qual:jar:2.11.1:runtime
> [INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:runtime
> [INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:runtime
> [INFO] |  +- org.apache.calcite:calcite-core:jar:1.27.0:runtime
> [INFO] |  |  +- org.apache.calcite:calcite-linq4j:jar:1.27.0:runtime
> [INFO] |  |  +- com.esri.geometry:esri-geometry-api:jar:2.2.0:runtime
> [INFO] |  |  +- org.apache.calcite.avatica:avatica-core:jar:1.18.0:runtime
> [INFO] |  |  |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.18.0:runtime
> [INFO] |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:runtime
> [INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.10.0:runtime
> [INFO] |  |  +- com.google.uzaygezen:uzaygezen-core:jar:0.2:runtime
> [INFO] |  |  |  \- log4j:log4j:jar:1.2.17:runtime
> [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.4.0:runtime
> [INFO] |  |  +- commons-codec:commons-codec:jar:1.13:runtime
> [INFO] |  |  +- net.hydromatic:aggdesigner-algorithm:jar:6.0:runtime
> [INFO] |  |  |  +- commons-lang:commons-lang:jar:2.4:runtime
> [INFO] |  |  |  \- commons-logging:commons-logging:jar:1.1.3:runtime
> [INFO] |  |  +- org.apache.commons:commons-dbcp2:jar:2.6.0:runtime
> [INFO] |  |  |  \- org.apache.commons:commons-pool2:jar:2.6.1:runtime
> [INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.8:runtime
> [INFO] |  |  \- commons-io:commons-io:jar:2.4:runtime
> [INFO] |  +- org.freemarker:freemarker:jar:2.3.31:runtime
> [INFO] |  +- com.facebook.presto:presto-parser:jar:0.238.2:runtime
> [INFO] |  |  +- javax.inject:javax.inject:jar:1:runtime
> [INFO] |  |  +- io.airlift:slice:jar:0.38:runtime
> [INFO] |  |  |  \- org.openjdk.jol:jol-core:jar:0.2:runtime
> [INFO] |  |  +- org.antlr:antlr4-runtime:jar:4.7.1:runtime
> [INFO] |  |  \- com.facebook.airlift:log:jar:0.191:runtime
> [INFO] |  +- com.squareup:javapoet:jar:1.11.1:runtime
> [INFO] |  +- com.google.ortools:ortools-java:jar:9.1.9490:runtime
> [INFO] |  |  +- com.google.ortools:ortools-linux-x86-64:jar:9.1.9490:runtime
> [INFO] |  |  +- com.google.ortools:ortools-darwin-x86-64:jar:9.1.9490:runtime
> [INFO] |  |  +- com.google.ortools:ortools-win32-x86-64:jar:9.1.9490:runtime
> [INFO] |  |  \- net.java.dev.jna:jna-platform:jar:5.8.0:runtime
> [INFO] |  |     \- net.java.dev.jna:jna:jar:5.8.0:runtime
> [INFO] |  \- com.google.protobuf:protobuf-java:jar:3.8.0:runtime
> [INFO] +- com.h2database:h2:jar:1.4.200:compile
> [INFO] +- org.jooq:jooq:jar:3.13.3:compile
> [INFO] |  +- org.reactivestreams:reactive-streams:jar:1.0.2:compile
> [INFO] |  \- javax.xml.bind:jaxb-api:jar:2.3.1:compile
> [INFO] |     \- javax.activation:javax.activation-api:jar:1.2.0:compile
> [INFO] +- org.jooq:jooq-meta-extensions:jar:3.13.3:compile
> [INFO] |  +- org.hibernate:hibernate-core:jar:5.4.9.Final:compile
> [INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
> [INFO] |  |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
> [INFO] |  |  +- org.javassist:javassist:jar:3.24.0-GA:compile
> [INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.2:compile
> [INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
> [INFO] |  |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
> [INFO] |  |  +- org.jboss:jandex:jar:2.1.1.Final:compile
> [INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
> [INFO] |  |  +- org.dom4j:dom4j:jar:2.1.1:compile
> [INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.0.Final:compile
> [INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
> [INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
> [INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
> [INFO] |  |     +- org.jvnet.staxex:stax-ex:jar:1.8:compile
> [INFO] |  |     \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
> [INFO] |  +- org.springframework:spring-context:jar:5.1.9.RELEASE:compile
> [INFO] |  |  +- org.springframework:spring-aop:jar:5.1.9.RELEASE:compile
> [INFO] |  |  +- org.springframework:spring-beans:jar:5.1.9.RELEASE:compile
> [INFO] |  |  +- org.springframework:spring-core:jar:5.1.9.RELEASE:compile
> [INFO] |  |  |  \- org.springframework:spring-jcl:jar:5.1.9.RELEASE:compile
> [INFO] |  |  \- org.springframework:spring-expression:jar:5.1.9.RELEASE:compile
> [INFO] |  \- org.liquibase:liquibase-core:jar:3.8.0:compile
> [INFO] |     +- org.yaml:snakeyaml:jar:1.23:compile
> [INFO] |     \- ch.qos.logback:logback-classic:jar:1.2.3:compile
> [INFO] |        \- ch.qos.logback:logback-core:jar:1.2.3:compile
> [INFO] +- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
> [INFO] +- org.apache.logging.log4j:log4j-core:jar:2.17.2:compile
> [INFO] \- commons-cli:commons-cli:jar:1.5.0:compile

**Comment by lalithsuresh** [comment]
@hunhoffe could you try explicitly specifying more recent protobuf versions in your project? 3.8.0 seems quite stale. Try 3.15.0 for example.

**Comment by hunhoffe** [comment]
Sure! I wasn't specifying any specific version of protobuf at all in my pom file because I don't use it directly.

When I added protobuf 3.19.4 to my pom file (I choose 3.19 instead of 3.15 due to vulnerabilities listed in maven repository for 3.15) it did fix the issue and I was able to solve successfully. Thank you!

Is the minimal protobuf version something that needs to be documented somewhere?

**Comment by lalithsuresh** [comment]
Glad it worked! Indeed, this is actually a workaround and protobuf versions being overridden is a common occurrence.

> Is the minimal protobuf version something that needs to be documented somewhere?

Yes it should be. Want to send me a PR? Otherwise I'll add it later.
